name: comment pull req
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            congratulations on making this pull request
